#  Algoritmo QR 

Este notebook explora el algoritmo QR usando conceptos y ejemplos numéricos.

## Introducción: ¿Qué es el algoritmo QR? 

El algoritmo QR es utilizado en el algebra vectorial para el calculo de valores y vectores propios (Eigenvectores) de una matriz. El método se basa en la "descomposición QR" desarrollada por John G.F. Francis y Vera Kublánovskaya de de manera independiente durante la decada de 1950.

La descomposición QR consiste en la representación de cualquier matriz regular H como un producto de la forma $H = QR$, donde $Q$ representa una matriz ortogonal y $R$ una matriz triangular superior. El algoritmo QR utiliza esta representación para encontrar los valores y vectores propios multiplicando la matriz a la inversa e iterando hasta que los valores se encuentran en la diagonal. Para mejor visualización de la descomposición QR se presenta el siguiente ejemplo:

Considerando la matriz $A$

$\begin{pmatrix}
1.0 & -1.0 & 4.0 \\
1.0 & 4.0 & -2.0 \\
1.0 & 4.0 & 2.0 \\
1.0 & -1.0 & 0.0
\end{pmatrix}$

La matriz de base ortonormal $Q$: 

$\begin{pmatrix}
-0.5 & 0.5 & -0.5 & -0.5 \\
-0.5 & -0.5 & 0.5 & -0.5 \\
-0.5 & -0.5 & -0.5 & 0.5 \\
-0.5 & 0.5 & 0.5 & 0.5 
\end{pmatrix}$

Y la matriz diagonal superior $R$: 

$\begin{pmatrix}
-2.0 & -3.0 & -2.0 \\
0.0 & -5.0 & 2.0 \\
0.0 & 0.0 & -4.0 \\
0.0 & -0.0 & -0.0
\end{pmatrix}$

Obtenemos que el producto de $Q$ y $R$ es la matriz inicial $A$: 

$\begin{pmatrix}
1.0 & -1.0 & 4.0 \\
1.0 & 4.0 & -2.0 \\
1.0 & 4.0 & 2.0 \\
1.0 & -1.0 & -6.66133814775*10^-16
\end{pmatrix}$



Una descripción básica del algoritmo como una lista de pasos se presenta a continuación: 

1. Se toma una matriz tridiagonal (o se convierte una matriz de su forma original a tridiagonal utilizando el método de Householder (ejemplo al final del notebook). 

2. La matriz tridiagonal $A_{1}$ se representa como un producto de la forma $A_{1}= QR$ (una descomposición QR).

3. Se define $A_{2}$ como un producto de la forma $A_{2}= RQ$.

4. Usando el inverso de $A_{1}$ en $A_{2}$ se genera una matriz cuyos valores propios de $A$ se encuentran en la diagonal.

El algoritmo QR puede ser desarrollado por medio de codigo, en este caso se presenta en el lenguaje de programación python

Como primer ejemplo tenémos un codigo simplificado, fácil de dijerir, el cual aprobecha una libreria de python llamada numpy para poder realizar la descomposición de la matirz A La propia libreria incluye los metodos de Gram smith y Householder

Explicando brevemente lo que la libreria hace de forma interna es la siguiente:

Para calcular Q el algoritmo se basa en el hecho de que la matriz ortogonal por Q va a darnos la matriz identidad, en base a eso usando gram shmith que ya esta contemplado internamente y con esto calcula Q

Para calcular R, multiplica la matriz ortogonal por la matirz original.

Aclaración: Esta es la forma más eficiente para realizar la descomposición QR, otros metodos investigados corren bajo la programación de python 2 y no son aptos para el entorno de jupyter. en conjunto con el notebook se encuentra un algoritmo hecho en python 2

In [1]:
import pprint
import numpy
#Importaciónd de numpy y libreria de algebra lineal
import numpy.linalg   # Libreria de algebra lineal


#Se invoca un array de numpy para ingresar la matriz

A = numpy.array([[6, 5, 0],
              [5, 1, 4],
              [0, 4, 3]])

#Luego las variables Q y R seran llenadas por el metodo QR de la librera de numpy

Q, R = numpy.linalg.qr(A)


#Finalmente imprimimos nuestras matrices 
print ("A:")
pprint.pprint(A)

print ("Q:")
pprint.pprint(Q)

print ("R:")
pprint.pprint(R)

A:
array([[6, 5, 0],
       [5, 1, 4],
       [0, 4, 3]])
Q:
array([[-0.76822128,  0.33265418, -0.54697099],
       [-0.6401844 , -0.39918502,  0.65636519],
       [-0.        ,  0.854396  ,  0.51962244]])
R:
array([[-7.81024968, -4.4812908 , -2.5607376 ],
       [ 0.        ,  4.68166987,  0.96644793],
       [ 0.        ,  0.        ,  4.18432806]])


Sin embargo es importante realizar un análisis adecuado de como programar este método de forma manual para llegar a tener una
mejor comprensión de este, lo cual es lo que se presenta a continuación

Recursos: 

Ejemplo de Método de HouseHolder para encontrar la matríz tridiagonal: 

La matriz simétrica $A$ = 

$\begin{pmatrix}
4 & 1 & -2 & 2 \\
1 & 2 & 0 & 1 \\
-2 & 0 & 3 & -2 \\
2 & 1 & -2 & -1 
\end{pmatrix}$

$a= -(1)(\sum_{j=2}^{4}\ a_j^2 = -3, r= (\frac{1}{2}(-3)^2-\frac{1}{2}(1)(-3))^\frac{1}{2}= \sqrt6,$

$w = (0, \frac{\sqrt6}{3},-\frac{\sqrt6}{6},\frac{\sqrt6}{6})^t,$

$p^1 =\begin{equation}
 \begin{pmatrix} 
 1 & 0 & 0 & 0 \\
 0 & 1 & 0 & 0 \\
 0 & 0 & 1 & 0 \\
 0 & 0 & 0 & 1 \\
 \end{pmatrix} 
 -2(\frac{\sqrt6}{6})^2
 \begin{pmatrix}
 0 \\
 2 \\
 -1 \\
 1
 \end{pmatrix}
\end{equation}
(0, 2, -1, 1)
=\begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & -\frac{1}{3} & \frac{2}{3} & -\frac{2}{3} \\
0 & \frac{2}{3} & \frac{2}{3} & \frac{1}{3} \\
0 & -\frac{2}{3} & \frac{1}{3} & \frac{2}{3}
 \end{pmatrix}$
 
Entonces

$\begin{equation}
A^2 =
 \begin{pmatrix} 
4 & -3 & 0 & 0 \\
-3 & \frac{10}{3} & 1 & \frac{4}{3} \\
0 & 1 & \frac{5}{3} & -\frac{4}{3} \\
0 & \frac{4}{3} & -\frac{4}{3} & -1
 \end{pmatrix} 
\end{equation}
$

$a = -\frac{5}{3}, r = \frac{2\sqrt5}{3}, w = (0,0,2\sqrt5, \frac{\sqrt5}{5})^t$, 

$\begin{equation}
p^2 =
 \begin{pmatrix} 
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0 \\
0 & 0 & -\frac{3}{5} & -\frac{4}{5} \\
0 & 0 & -\frac{4}{5} & \frac{3}{5}
 \end{pmatrix} 
\end{equation}$

La matriz tridiagonal simétrica $A^3$ es: 

$\begin{equation}
A^3 =
 \begin{pmatrix} 
4 & -3 & 0 & 0 \\
-3 & \frac{10}{3} & -\frac{5}{3} & 0 \\
0 & -\frac{5}{3} & -\frac{33}{25} & \frac{68}{75} \\
0 & 0 & \frac{68}{75} & \frac{149}{75}
 \end{pmatrix} 
\end{equation}$
